In [2]:
import pandas as pd
dict1 = {
    "name": ["Ford Mustang", "BMW", "BYD", "Supra", "Lamborgini", "Porsche"],
    "seat": [4, 5, 5, 2, 2, 2]
}
dict2=pd.DataFrame(dict1)
print(dict1)
print(dict2)
print("Version:", pd.__version__)

pd.Series(dict1)

print(dict2['name'])

print(pd.Series(dict1,index=[1,2,3,4,5,6]))

{'name': ['Ford Mustang', 'BMW', 'BYD', 'Supra', 'Lamborgini', 'Porsche'], 'seat': [4, 5, 5, 2, 2, 2]}
           name  seat
0  Ford Mustang     4
1           BMW     5
2           BYD     5
3         Supra     2
4    Lamborgini     2
5       Porsche     2
Version: 2.2.3
0    Ford Mustang
1             BMW
2             BYD
3           Supra
4      Lamborgini
5         Porsche
Name: name, dtype: object
1    NaN
2    NaN
3    NaN
4    NaN
5    NaN
6    NaN
dtype: object

In [3]:
a=["a","b","c","d"]
mypd=pd.Series(a)
print(mypd)

0    a
1    b
2    c
3    d
dtype: object

In [4]:
a=["a","b","c","d"]
mypd=pd.Series(a,index=[1,2,3,4])
print(mypd[1])

a

In [5]:
A={
    "day1":"Monday",
    "day2":"Tuesday",
    "day3":"Wednesday"
}
p=pd.Series(A)
print(p.loc["day1"])

Monday

In [8]:
from google.colab import files

uploaded = files.upload()

Saving laptopData.csv to laptopData.csv

In [9]:
df=pd.read_csv("/content/laptopData.csv")

In [10]:
print(df)

      Unnamed: 0 Company            TypeName Inches  \
0            0.0   Apple           Ultrabook   13.3
1            1.0   Apple           Ultrabook   13.3
2            2.0      HP            Notebook   15.6
3            3.0   Apple           Ultrabook   15.4
4            4.0   Apple           Ultrabook   13.3
...          ...     ...                 ...    ...
1298      1298.0  Lenovo  2 in 1 Convertible     14
1299      1299.0  Lenovo  2 in 1 Convertible   13.3
1300      1300.0  Lenovo            Notebook     14
1301      1301.0      HP            Notebook   15.6
1302      1302.0    Asus            Notebook   15.6

                                ScreenResolution  \
0             IPS Panel Retina Display 2560x1600
1                                       1440x900
2                              Full HD 1920x1080
3             IPS Panel Retina Display 2880x1800
4             IPS Panel Retina Display 2560x1600
...                                          ...
1298   IPS Panel Full HD / Touchscreen 1920x1080
1299  IPS Panel Quad HD+ / Touchscreen 3200x1800
1300                                    1366x768
1301                                    1366x768
1302                                    1366x768

                                       Cpu   Ram               Memory  \
0                     Intel Core i5 2.3GHz   8GB            128GB SSD
1                     Intel Core i5 1.8GHz   8GB  128GB Flash Storage
2               Intel Core i5 7200U 2.5GHz   8GB            256GB SSD
3                     Intel Core i7 2.7GHz  16GB            512GB SSD
4                     Intel Core i5 3.1GHz   8GB            256GB SSD
...                                    ...   ...                  ...
1298            Intel Core i7 6500U 2.5GHz   4GB            128GB SSD
1299            Intel Core i7 6500U 2.5GHz  16GB            512GB SSD
1300  Intel Celeron Dual Core N3050 1.6GHz   2GB   64GB Flash Storage
1301            Intel Core i7 6500U 2.5GHz   6GB              1TB HDD
1302  Intel Celeron Dual Core N3050 1.6GHz   4GB            500GB HDD

                               Gpu       OpSys  Weight        Price
0     Intel Iris Plus Graphics 640       macOS  1.37kg   71378.6832
1           Intel HD Graphics 6000       macOS  1.34kg   47895.5232
2            Intel HD Graphics 620       No OS  1.86kg   30636.0000
3               AMD Radeon Pro 455       macOS  1.83kg  135195.3360
4     Intel Iris Plus Graphics 650       macOS  1.37kg   96095.8080
...                            ...         ...     ...          ...
1298         Intel HD Graphics 520  Windows 10   1.8kg   33992.6400
1299         Intel HD Graphics 520  Windows 10   1.3kg   79866.7200
1300             Intel HD Graphics  Windows 10   1.5kg   12201.1200
1301            AMD Radeon R5 M330  Windows 10  2.19kg   40705.9200
1302             Intel HD Graphics  Windows 10   2.2kg   19660.3200

[1303 rows x 12 columns]

In [11]:
df.isnull()

,Unnamed: 0,Company,TypeName,Inches,ScreenResolution,Cpu,Ram,Memory,Gpu,OpSys,Weight,Price
0,False,False,False,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...
1298,False,False,False,False,False,False,False,False,False,False,False,False
1299,False,False,False,False,False,False,False,False,False,False,False,False
1300,False,False,False,False,False,False,False,False,False,False,False,False
1301,False,False,False,False,False,False,False,False,False,False,False,False
1302,False,False,False,False,False,False,False,False,False,False,False,False

In [12]:
df.isnull().sum()

Unnamed: 0          30
Company             30
TypeName            30
Inches              30
ScreenResolution    30
Cpu                 30
Ram                 30
Memory              30
Gpu                 30
OpSys               30
Weight              30
Price               30
dtype: int64

In [13]:
df.duplicated()

0       False
1       False
2       False
3       False
4       False
        ...
1298    False
1299    False
1300    False
1301    False
1302    False
Length: 1303, dtype: bool

In [14]:
df.drop_duplicates(inplace = True)

In [15]:
print(df)

      Unnamed: 0 Company            TypeName Inches  \
0            0.0   Apple           Ultrabook   13.3
1            1.0   Apple           Ultrabook   13.3
2            2.0      HP            Notebook   15.6
3            3.0   Apple           Ultrabook   15.4
4            4.0   Apple           Ultrabook   13.3
...          ...     ...                 ...    ...
1298      1298.0  Lenovo  2 in 1 Convertible     14
1299      1299.0  Lenovo  2 in 1 Convertible   13.3
1300      1300.0  Lenovo            Notebook     14
1301      1301.0      HP            Notebook   15.6
1302      1302.0    Asus            Notebook   15.6

                                ScreenResolution  \
0             IPS Panel Retina Display 2560x1600
1                                       1440x900
2                              Full HD 1920x1080
3             IPS Panel Retina Display 2880x1800
4             IPS Panel Retina Display 2560x1600
...                                          ...
1298   IPS Panel Full HD / Touchscreen 1920x1080
1299  IPS Panel Quad HD+ / Touchscreen 3200x1800
1300                                    1366x768
1301                                    1366x768
1302                                    1366x768

                                       Cpu   Ram               Memory  \
0                     Intel Core i5 2.3GHz   8GB            128GB SSD
1                     Intel Core i5 1.8GHz   8GB  128GB Flash Storage
2               Intel Core i5 7200U 2.5GHz   8GB            256GB SSD
3                     Intel Core i7 2.7GHz  16GB            512GB SSD
4                     Intel Core i5 3.1GHz   8GB            256GB SSD
...                                    ...   ...                  ...
1298            Intel Core i7 6500U 2.5GHz   4GB            128GB SSD
1299            Intel Core i7 6500U 2.5GHz  16GB            512GB SSD
1300  Intel Celeron Dual Core N3050 1.6GHz   2GB   64GB Flash Storage
1301            Intel Core i7 6500U 2.5GHz   6GB              1TB HDD
1302  Intel Celeron Dual Core N3050 1.6GHz   4GB            500GB HDD

                               Gpu       OpSys  Weight        Price
0     Intel Iris Plus Graphics 640       macOS  1.37kg   71378.6832
1           Intel HD Graphics 6000       macOS  1.34kg   47895.5232
2            Intel HD Graphics 620       No OS  1.86kg   30636.0000
3               AMD Radeon Pro 455       macOS  1.83kg  135195.3360
4     Intel Iris Plus Graphics 650       macOS  1.37kg   96095.8080
...                            ...         ...     ...          ...
1298         Intel HD Graphics 520  Windows 10   1.8kg   33992.6400
1299         Intel HD Graphics 520  Windows 10   1.3kg   79866.7200
1300             Intel HD Graphics  Windows 10   1.5kg   12201.1200
1301            AMD Radeon R5 M330  Windows 10  2.19kg   40705.9200
1302             Intel HD Graphics  Windows 10   2.2kg   19660.3200

[1274 rows x 12 columns]

In [16]:
df.dropna(inplace = True)

In [17]:
print(df)

      Unnamed: 0 Company            TypeName Inches  \
0            0.0   Apple           Ultrabook   13.3
1            1.0   Apple           Ultrabook   13.3
2            2.0      HP            Notebook   15.6
3            3.0   Apple           Ultrabook   15.4
4            4.0   Apple           Ultrabook   13.3
...          ...     ...                 ...    ...
1298      1298.0  Lenovo  2 in 1 Convertible     14
1299      1299.0  Lenovo  2 in 1 Convertible   13.3
1300      1300.0  Lenovo            Notebook     14
1301      1301.0      HP            Notebook   15.6
1302      1302.0    Asus            Notebook   15.6

                                ScreenResolution  \
0             IPS Panel Retina Display 2560x1600
1                                       1440x900
2                              Full HD 1920x1080
3             IPS Panel Retina Display 2880x1800
4             IPS Panel Retina Display 2560x1600
...                                          ...
1298   IPS Panel Full HD / Touchscreen 1920x1080
1299  IPS Panel Quad HD+ / Touchscreen 3200x1800
1300                                    1366x768
1301                                    1366x768
1302                                    1366x768

                                       Cpu   Ram               Memory  \
0                     Intel Core i5 2.3GHz   8GB            128GB SSD
1                     Intel Core i5 1.8GHz   8GB  128GB Flash Storage
2               Intel Core i5 7200U 2.5GHz   8GB            256GB SSD
3                     Intel Core i7 2.7GHz  16GB            512GB SSD
4                     Intel Core i5 3.1GHz   8GB            256GB SSD
...                                    ...   ...                  ...
1298            Intel Core i7 6500U 2.5GHz   4GB            128GB SSD
1299            Intel Core i7 6500U 2.5GHz  16GB            512GB SSD
1300  Intel Celeron Dual Core N3050 1.6GHz   2GB   64GB Flash Storage
1301            Intel Core i7 6500U 2.5GHz   6GB              1TB HDD
1302  Intel Celeron Dual Core N3050 1.6GHz   4GB            500GB HDD

                               Gpu       OpSys  Weight        Price
0     Intel Iris Plus Graphics 640       macOS  1.37kg   71378.6832
1           Intel HD Graphics 6000       macOS  1.34kg   47895.5232
2            Intel HD Graphics 620       No OS  1.86kg   30636.0000
3               AMD Radeon Pro 455       macOS  1.83kg  135195.3360
4     Intel Iris Plus Graphics 650       macOS  1.37kg   96095.8080
...                            ...         ...     ...          ...
1298         Intel HD Graphics 520  Windows 10   1.8kg   33992.6400
1299         Intel HD Graphics 520  Windows 10   1.3kg   79866.7200
1300             Intel HD Graphics  Windows 10   1.5kg   12201.1200
1301            AMD Radeon R5 M330  Windows 10  2.19kg   40705.9200
1302             Intel HD Graphics  Windows 10   2.2kg   19660.3200

[1273 rows x 12 columns]

In [20]:
print(df.corr(numeric_only=True))

            Unnamed: 0     Price
Unnamed: 0    1.000000  0.065403
Price         0.065403  1.000000